import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToggleThemeButton } from "@/components/ui/ToggleThemeButton";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="dark">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="root-layout-wrapper p-6">
                    <div className="flex items-center mb-4 pb-4 border-b border-red-600 dark:border-neutral-900 justify-between">
                        <h1>PDS Manager</h1>
                        <ToggleThemeButton />
                    </div>
                    <div className="flex flex-col items-center">{children}</div>
                </div>
            </body>
        </html>
    );
}
