import "./globals.css";
import { ToggleThemeButton } from "@/components/ui/ToggleThemeButton";

import { Poppins, Montserrat, Inter, Raleway } from "next/font/google";

const raleway = Raleway({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-inter",
});

// const montserrat = Montserrat({
//     subsets: ["latin"],
//     weight: ["400", "500", "600"],
//     variable: "--font-montserrat",
// });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="dark">
            <body className={`${raleway.variable} antialiased`}>
                <div className="root-layout-wrapper">
                    {/* <div className="flex items-center py-4 border-b border-red-600 dark:border-neutral-900 justify-between">
                        <h1>PDS Manager</h1>
                        <ToggleThemeButton />
                    </div> */}
                    <div>{children}</div>
                </div>
            </body>
        </html>
    );
}
