import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { ToggleThemeButton } from "@/components/ui/ToggleThemeButton";

import { Poppins, Montserrat, Inter, Raleway } from "next/font/google";

const raleway = Raleway({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-inter",
});

// const montserrat = Montserrat({
//     subsets: ["latin"],
//     weight: ["400", "500", "600"],
//     variable: "--font-montserrat",
// });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="dark">
            <body className={`${raleway.variable} antialiased`}>
                <div className="root-layout-wrapper text-neutral-700 dark:text-neutral-300 flex justify-center mask-auto border-white">
                    <div className="max-w-[2200px] w-full">{children}</div>
                </div>
                <Toaster position="top-center" richColors />
            </body>
        </html>
    );
}
